zavod-96-ru/routes/web.php
<?php

use App\Http\Controllers\AmoController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\CatalogController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\FormController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InfoController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\SearchController;
use Illuminate\Support\Facades\Route;
use Spatie\Sitemap\SitemapGenerator;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/privacy', [HomeController::class, 'privacy'])->name('home.privacy');

Route::get('/catalog', [CatalogController::class, 'index'])->name('catalog.index');
Route::get('/catalog/{category}', [CatalogController::class, 'category'])->name('catalog.category');
Route::get('/catalog/{category}/{product}', [CatalogController::class, 'product'])->name('catalog.product');

Route::get('/contacts', [ContactController::class, 'index'])->name('contact.index');

Route::get('/company', [CompanyController::class, 'index'])->name('company.index');
Route::get('/company/reviews', [CompanyController::class, 'review'])->name('company.review');
Route::get('/company/payment', [CompanyController::class, 'payment'])->name('company.payment');
Route::get('/company/delivery', [CompanyController::class, 'delivery'])->name('company.delivery');
Route::get('/company/requisites', [CompanyController::class, 'requisites'])->name('company.requisites');
Route::get('/company/licenses/', [CompanyController::class, 'licenses'])->name('company.licenses');
Route::get('/company/price/', [CompanyController::class, 'price'])->name('company.price');

Route::get('/info/oprosnye-listy', [InfoController::class, 'questionnaire'])->name('info.questionnaire');
Route::get('/info/chertezhi', [InfoController::class, 'blueprint'])->name('info.blueprint');

Route::get('/info/articles', [ArticleController::class, 'index'])->name('article.index');
Route::get('/info/articles/{slug}', [ArticleController::class, 'show'])->name('article.show');

Route::get('/search', [SearchController::class, 'index'])->name('search.index');

Route::post('form/callback', [FormController::class,'callback'])->name('form.callback'); 
Route::post('form/question', [FormController::class,'question'])->name('form.question'); 
Route::post('form/order', [FormController::class,'order'])->name('form.order'); 

Route::get('amo/gettoken', [AmoController::class,'getToken'])->name('amo.getToken');


Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::get('/sitemap', function () {
    SitemapGenerator::create('https://zavod-96.ru')->writeToFile(public_path('sitemap.xml'));
    return 'Sitemap generated successfully.';
});

require __DIR__.'/auth.php';

zavod-96-ru/app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;

class Product extends Model
{
    use HasFactory;
    
    protected $fillable = [
        'title',
        'slug',
        'preview_image',
        'detail_image',
        'preview_text',
        'detail_text',
        'category_id',
        'price',
        'seo_title',
        'seo_description',
        'sort'
    ];

    public function category()
    {
        return $this->belongsTo(ProductCategory::class, 'category_id');
    }

    public function getFormattedPriceAttribute()
    {
        return number_format($this->price, 0, '', ' ');
    }
}

zavod-96-ru/app/Http/Controllers/CatalogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\ProductCategory;
use Illuminate\Http\Request;

class CatalogController extends Controller
{
    public $component_title = 'Каталог продукции';

    public function index() {
        $pageTitle = $this->component_title;

        $categories = ProductCategory::query()->whereNull('parent_id')->orderBy('sort', 'asc')->get();
        $favorite_products = Product::query()->where('favorite', true)->get();

        $breadcrumb_items = [
            [ 'title' => $pageTitle, 'current' => true ],
        ];

        return view('catalog.index', compact(['pageTitle','breadcrumb_items', 'categories', 'favorite_products']));
    }

    public function category($category)
    {
        $currentCategory = ProductCategory::where('slug', $category)->firstOrFail();
        $products = Product::where('category_id', $currentCategory->id)->orderBy('sort', 'asc')->get();
        
        $pageTitle = $currentCategory->title;
        
        $categoriesMenu = $this->getCategoriesTree($currentCategory->slug);

        $breadcrumb_items = [
            [ 'title' => $this->component_title, 'route' => 'catalog.index', 'current' => false],            
        ];

        $path = $this->findCategoryPath($currentCategory->slug);

        foreach ($path as $slug) {
            if($slug == end($path)) break;
            $pathCategody = ProductCategory::where('slug', $slug)->firstOrFail();
            $breadcrumb_items[] = [ 'title' => $pathCategody->title, 'route' => 'catalog.category', 'route_params' => [$slug], 'current' => false];
        }

        $breadcrumb_items[] = [ 'title' => $pageTitle, 'current' => true ];

        return view('catalog.category', compact([
            'currentCategory',
            'products', 
            'categoriesMenu', 
            'pageTitle',
            'breadcrumb_items'
        ]));   
    }

    public function product($category, $product)
    {
        $product = Product::where('slug', $product)->firstOrFail();
        $pageTitle = $product->title;
        $favorite_products = Product::query()->where('favorite', true)->get();

        $currentCategory = ProductCategory::where('slug', $category)->firstOrFail();

        $categoriesMenu = $this->getCategoriesTree($currentCategory->slug);

        $breadcrumb_items = [
            [ 'title' => $this->component_title, 'route' => 'catalog.index', 'current' => false],            
        ];

        $path = $this->findCategoryPath($currentCategory->slug);

        foreach ($path as $slug) {
            $pathCategody = ProductCategory::where('slug', $slug)->firstOrFail();
            $breadcrumb_items[] = [ 'title' => $pathCategody->title, 'route' => 'catalog.category', 'route_params' => [$slug], 'current' => false];
        }

        $breadcrumb_items[] = [ 'title' => $pageTitle, 'current' => true ];

        return view('catalog.product', compact([
            'product',
            'favorite_products', 
            'categoriesMenu', 
            'pageTitle',
            'breadcrumb_items'
        ]));

    }

    private function getCategoriesTree($slug)
    {
        $path = $this->findCategoryPath($slug);

        // Получаем все категории без родителей (верхний уровень)
        $topCategories = ProductCategory::whereNull('parent_id')->get();

        // Создаем массив для древовидного меню
        $menu = [];

        // Рекурсивная функция для построения дерева
        $buildTree = function ($categories) use (&$buildTree, $path) {
            $tree = [];

            foreach ($categories as $category) {
                $node = $category->toArray();
                $node['children'] = $buildTree($category->children);
                $node['active'] = in_array($category->slug, $path);
                $tree[] = $node;
            }

            return $tree;
        };

        // Перебираем верхние категории и строим древовидное меню
        foreach ($topCategories as $topCategory) {
            $menu[] = [
                'id' => $topCategory->id,
                'title' => $topCategory->title,
                'slug' => $topCategory->slug,
                'active' => in_array($topCategory->slug, $path),
                'children' => $buildTree($topCategory->children),
            ];
        }

        return $menu;
    }

    public function findCategoryPath($slug)
    {
        // Находим категорию по slug
        $category = ProductCategory::where('slug', $slug)->first();

        // Если категория не найдена, можно вернуть, например, ошибку или пустой массив
        if (!$category) {
            return ['error' => 'Category not found.'];
        }

        // Рекурсивная функция для построения пути
        $buildPath = function ($category) {
            $path = [];

            while ($category->parent) {
                $path[] = $category->parent->slug;
                $category = $category->parent;
            }

            return array_reverse($path);
        };

        // Строим путь
        $categoryPath = $buildPath($category);

        // Теперь $categoryPath содержит путь в виде массива
        $categoryPath[] = $slug;
        return $categoryPath;
    }
}

zavod-96-ru/resources/views/catalog/category.blade.php
@extends('layouts.main')

@section('page.title',  __($pageTitle) . ' | ' . config('seo.title'))
@section('page.description', config('seo.description') . '. ' . __($pageTitle))

@section('content')
    <div class="catalog-page padb">
        <div class="container">
            <h1>{{ __($pageTitle) }}</h1>
            <div class="row">
                <div class="col-lg-3 category-left">
                    {{-- CATEGORIES MENU --}}
                    @include('blocks.menu.categories')
                </div>

                <div class="col-lg-9 category-right">
                    @if (count($currentCategory->children))
                        <div class="category-block padb">
                            <div class="row">

                                @foreach ($currentCategory->children as $subcategory)
                                    <div class="col-md-6">
                                        <a href="{{ route('catalog.category', $subcategory->slug) }}" class="cat-blk">
                                            <div class="cat-blk-image">
                                                <img src="/uploads/{{ $subcategory->preview_image }}"
                                                    alt="{{ $subcategory->title }}">
                                            </div>
                                            <span>{{ $subcategory->title }}</span>
                                        </a>
                                    </div>
                                @endforeach

                            </div>
                        </div>
                    @endif
                    @if (count($products))
                        <div class="category-prod">
                            <div class="row">
                                @foreach ($products as $product)
                                    <div class="col-md-4 col-6">
                                        <a href="{{route('catalog.product', [$currentCategory->slug, $product->slug])}}" class="catalog-product">
                                            <div class="catalog-product-image">
                                                <img src="/uploads/{{$product->preview_image}}" alt="{{$product->title}}">
                                            </div>
                                            <div class="catalog-product-description">
                                                <span class="catalog-product-title">{{$product->title}}</span>
                                                <span class="catalog-product-prise">
                                                    @if ($product->price > 0)
                                                        от {{ $product->formatted_price}} руб.
                                                    @else
                                                        цена по запросу
                                                    @endif
                                                </span>
                                            </div>
                                        </a>
                                    </div>
                                @endforeach                                
                            </div>
                        </div>
                    @endif


                    <div class="category-content">
                        {!! $currentCategory->detail_text !!}
                    </div>
                </div>
            </div>
        </div>
    </div>


    {{-- ORDER --}}
    @include('blocks.order')

    {{-- PROPOSE --}}
    @include('blocks.propose')

@endsection

zavod-96-ru/resources/views/catalog/index.blade.php
@extends('layouts.main')

@section('page.title',  __($pageTitle) . ' | ' . config('seo.title'))
@section('page.description', config('seo.description') . '. ' . __($pageTitle))

@section('content')
    <div class="catalog-page padb">
        <div class="container">
            <h1>{{ __($pageTitle) }}</h1>
            <div class="info-text">
                <p>Производственное Объединение STELZ предлагает Вам полный перечень электротехнического оборудования,
                    напряжением от 6 Кв до 35 Кв и мощностью до 6300 кВа.</p>
            </div>

            <div class="catalog-block row">
                @foreach ($categories as $category)
                    <div class="col-lg-4 col-sm-6">
                        <a href="{{ route('catalog.category', $category->slug) }}" class="catblk">
                            <span>{{ $category->title }}</span>
                            <img src="/uploads/{{ $category->preview_image }}" alt="{{ $category->title }}">
                        </a>
                    </div>
                @endforeach
            </div>

        </div>
    </div>



    {{-- CONNECT --}}
    @include('blocks.connect')

    {{-- FAVORITE PRODUCTS --}}
    @include('blocks.catalog.favorite', ['favorite_products' => $favorite_products])

    {{-- ORDER --}}
    @include('blocks.order')

    {{-- PROPOSE --}}
    @include('blocks.propose')

@endsection

zavod-96-ru/resources/views/catalog/product.blade.php
@extends('layouts.main')

@section('page.title',  __($pageTitle) . ' | ' . config('seo.title'))
@section('page.description', config('seo.description') . '. ' . __($pageTitle))

@section('content')
    <div class="catalog-page padb">
        <div class="container">            
            <div class="row">
                <div class="col-lg-3 category-left">
                    {{-- CATEGORIES MENU --}}
                    @include('blocks.menu.categories')
                </div>

                <div class="col-lg-9 category-right">
                    <div class="card-product">
                        <div class="card-block d-flex">
                            <div class="card-image">
                                <img src="/uploads/{{ $product->detail_image }}" alt="{{ $product->title }}">
                            </div>
                            <div class="card-info">
                                <h1 class="title-h3">{{ __($pageTitle) }}</h1>

                                <span class="product-prise">
                                    @if ($product->price > 0)
                                        от {{ $product->formatted_price}} руб.
                                    @else
                                        цена по запросу
                                    @endif
                                </span>
                                <p>Чтобы купить {{ $product->title }}, опишите ее или прикрепите опросный лист и
                                    отправьте нам — и Вы получите бесплатный расчет в течение 1 дня</p>
                                <a href="{{route('info.questionnaire')}}" class="red">Заполнить опросный лист&gt;</a>
                                <button type="button" class="btn btn-danger btn-arrow" data-bs-toggle="modal"
                                    data-bs-title="Оставить заявку" data-bs-target="#Online-order" data-product_name="{{ $product->title }}">Оставить заявку</button>
                            </div>
                        </div>
                    </div>


                    <div class="category-content">
                        {!! $product->detail_text !!}
                    </div>
                </div>
            </div>
        </div>
    </div>

    {{-- QUESTION --}}
    @include('blocks.question')

    {{-- FAVORITE PRODUCTS --}}
    @include('blocks.catalog.favorite', ['favorite_products' => $favorite_products])

    {{-- ORDER --}}
    @include('blocks.order')

    {{-- PROPOSE --}}
    @include('blocks.propose')

@endsection